default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        automatic_attendance:
          class: MarkAttendanceJob
          args: []
          schedule: "* 23 * * *"
development:
  <<: *default
