default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default